language: objective-c
osx_image: xcode8.3
cache: cocoapods
env:
  global:
  - IOS_SDK=iphonesimulator10.3
  - WORKSPACE=YapTaskQueue.xcworkspace
  - POD_WORKSPACE=YapTaskQueueSpecTest/YapTaskQueueSpecTest.xcworkspace
  - IOS_FRAMEWORK_SCHEME=YapTaskQueue
  - POD_IOS_FRAMEWORK_SCHEME=YapTaskQueueSpecTest
  matrix:
    - DESTINATION="OS=10.3,name=iPhone 7"     POD_LINT="NO"
script:
  - pod update
  - pod update --project-directory=YapTaskQueueSpecTest/
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
  - xcodebuild -workspace "$POD_WORKSPACE" -scheme "$POD_IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --allow-warnings;
    fi
