language: objective-c
osx_image: xcode8.2
cache: cocoapods
env:
  global:
  - IOS_SDK=iphonesimulator9.3
  - WORKSPACE=YapTaskQueue.xcworkspace
  - POD_WORKSPACE=YapTaskQueueSpecTest/YapTaskQueueSpecTest.xcworkspace
  - IOS_FRAMEWORK_SCHEME=YapTaskQueue
  - POD_IOS_FRAMEWORK_SCHEME=YapTaskQueueSpecTest
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"          POD_LINT="YES"
    - DESTINATION="OS=8.2,name=iPhone 5"           POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S"          POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6"           POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6"           POD_LINT="NO"
    - DESTINATION="OS=9.1,name=iPhone 6 Plus"      POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6S"          POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6S Plus"     POD_LINT="NO"
script:
  - pod update
  - pod update --project-directory=YapTaskQueueSpecTest/
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
  - xcodebuild -workspace "$POD_WORKSPACE" -scheme "$POD_IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --allow-warnings;
    fi
